### ISSUE TITLE
Prompt (& title bar) lack Git branch

### ISSUE THREAD

**Issue by MarkDBlackwell** [fedelibre/LilyDevDebian#7]
> The changes I made include the Git branch [in the] prompt, [as [promised] in the LilyPond Contributor Guide](http://lilypond.org/doc/v2.19/Documentation/contributor/setting-up#configuring-git). I would stick with what the LilyPond manual [promises]. Please test any change on the current LilyDev [repository], which runs Debian Jessie and does have bash_completion.
> 
> `export PS1="\h:\w\$(__git_ps1)$ "`

On Debian stretch, using your current LilyDev repository, I built an ISO and installed it successfully. After doing `cd ~/lilypond-git` (there), the Git branch appears neither in the prompt nor in `LXTerminal`'s title bar.

I notice the current LilyDev repository (commit 3e780d138e2c3c30aa945fa112e90daae47f8db5) lacks `\$(__git_ps1)` in lines [one](https://github.com/fedelibre/LilyDev/blob/3e780d138e2c3c30aa945fa112e90daae47f8db5/config/includes.chroot/etc/skel/.bashrc#L69), [two](https://github.com/fedelibre/LilyDev/blob/3e780d138e2c3c30aa945fa112e90daae47f8db5/config/includes.chroot/etc/skel/.bashrc#L60) and [three](https://github.com/fedelibre/LilyDev/blob/3e780d138e2c3c30aa945fa112e90daae47f8db5/config/includes.chroot/etc/skel/.bashrc#L62) of `skel/.bashrc` and the resulting `~/.bashrc`. BTW, inside double quotes (ref. line [one](https://github.com/fedelibre/LilyDev/blob/3e780d138e2c3c30aa945fa112e90daae47f8db5/config/includes.chroot/etc/skel/.bashrc#L69)) this syntax will succeed.

However, inside single quotes (ref. lines [two](https://github.com/fedelibre/LilyDev/blob/3e780d138e2c3c30aa945fa112e90daae47f8db5/config/includes.chroot/etc/skel/.bashrc#L60) and [three](https://github.com/fedelibre/LilyDev/blob/3e780d138e2c3c30aa945fa112e90daae47f8db5/config/includes.chroot/etc/skel/.bashrc#L62)), the syntax that will be successful is `$(__git_ps1)`: excluding the backslash `\`.

BTW, the current CG (version 2.19.24) otherwise mentions PS1 only here:
- [11.2 Minor release checklist](http://lilypond.org/doc/v2.19/Documentation/contributor/minor-release-checklist) section _Pre-release_ says "5. Prepare GUB environment by running:"

``` sh
### my-bashrc
export PS1="\[\e[1;33mGUB-ENV \w\]$ \[\e[0m\]"
export PATH=$PATH
export TERM=xterm
```

These presumably are general instructions for machines beyond the LilyDev ISO. @gperciva, is `my-bashrc` a file in your [GUB](http://github.com/gperciva/gub) repository, or generated by it? If so, I couldn't find it.

Section _Building GUB_ of CG's [11.5 Notes on builds with GUB](http://lilypond.org/doc/v2.19/Documentation/contributor/notes-on-builds-with-gub) says "GUB – the [Grand Unified Builder](http://lilypond.org/doc/v2.19/Documentation/contributor/other-repositories#grand-unified-builder-_0028gub_0029) – is used to build the release versions of LilyPond. The simplest way to set up a GUB build environment is to use a virtual machine with [LilyDev](http://lilypond.org/doc/v2.19/Documentation/contributor/lilydev)." Section [What is GUB](http://lilypond.org/gub/) of the _GUB – Grand Unified Builder_ website homepage explains GUB is "for turnkey building of all LilyPond [and certain other] binary installers."

See also #4.

**Comment by gperciva** [comment]
`my-bashrc` is the  three (or four) lines you quoted above.  My habit at that time, when writing documentation, was to begin a file with the filename (commented out).

It took me a while to remember what was happening, but here it is:
- my university computer back in 2009 was behind a nasty firewall, which required the HTTP_PROXY
- also, GUB rebuilds stuff if/when the environment changes.  That's fine, but if I installed a binary (say, blender-2.49a) by copying it somewhere and simply adding that directory to my $PATH, GUB would spend 12 hours rebuilding everything.
- to avoid that, I made a "limited" environment in which to build GUB.  (this would probably be better as a chroot or something new and funky)
- I kept a mental note to never attempt to build GUB unless my prompt said "GUB-ENV".
- `my-gub.sh` and `my-bashrc` set up the minimal "limited" environment which worked.

Some of the above story won't be relevant to people, but the general idea of avoiding unnecessary recomputation by keeping with a known environment is still valid.
(of course, it would help if somebody added this to the CG for future reference)

**Comment by fedelibre** [comment]
Il giorno ven 7 ago 2015 alle 23:03, Mark D. Blackwell 
notifications@github.com ha scritto:

> On Debian stretch, using your current LilyDev repository, I built an 
> ISO and installed it successfully. After doing cd ~/lilypond-git 
> (there), the Git branch appears neither in the prompt nor in 
> LXTerminal's title bar.

Because I haven't added the PS1 variable yet. Before leaving for 
holidays I was trying to find a way to append our variables to the 
default bashrc, as we were discussing on pull #4. I'm stuck here:
https://lists.debian.org/debian-live/2015/08/msg00020.html

If preseed does not work I'll use the lilydev-setup.sh script instead.
I'll be back in September.
