### ISSUE TITLE
missing install-info

### ISSUE THREAD

**Issue by de-wolff** [fedelibre/LilyDevDebian#9]
when using lilydev 4.1, out of the box make install will not work because of missing install-info.

an apt-get install install-info is needed, to be able to do make install

**Comment by fedelibre** [comment]
Thanks for the information, but the [Contributor Guide](http://lilypond.org/doc/v2.19/Documentation/contributor/compiling-with-lilydev) suggests not to install, as it's not needed for contributing to LilyPond:

Installing

>Don’t. There is no reason to install LilyPond within LilyDev. All development work can (and should) >stay within the ‘$LILYPOND_GIT’ directory, and any personal composition or typesetting work should >be done with an official GUB release.
